DROP TABLE genres IF EXISTS CASCADE;
DROP TABLE films_mpa IF EXISTS CASCADE;
DROP TABLE film_genre IF EXISTS CASCADE;
DROP TABLE films IF EXISTS CASCADE;
DROP TABLE friends IF EXISTS CASCADE;
DROP TABLE user_likes IF EXISTS CASCADE;
DROP TABLE users IF EXISTS CASCADE;
CREATE TABLE IF NOT EXISTS genres
(
    genre_id int NOT NULL,
    genre_name varchar(50),
    CONSTRAINT genre_id PRIMARY key(genre_id)
    );
CREATE TABLE IF NOT EXISTS films_mpa
(
    mpa_id int NOT NULL,
    mpa_name varchar(50) NOT NULL,
    CONSTRAINT mpa_id PRIMARY key(mpa_id)
    );
CREATE TABLE IF NOT EXISTS films
(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(200) NOT NULL,
    film_description varchar(200),
    film_releaseDate timestamp,
    film_duration int NOT NULL,
    film_rate int,
    mpa_id int,
    CONSTRAINT fk_mpa_id FOREIGN KEY(mpa_id) REFERENCES films_mpa(mpa_id)
    );
CREATE TABLE IF NOT EXISTS film_genre
(
    film_id int NOT NULL,
    genre_id int NOT NULL,
    CONSTRAINT fk_film_id FOREIGN KEY(film_id) REFERENCES films(film_id),
    CONSTRAINT fk_genre_id FOREIGN KEY(genre_id) REFERENCES genres(genre_id)
    );
CREATE TABLE IF NOT EXISTS users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email varchar(50) NOT NULL,
    user_login varchar(30) NOT NULL,
    user_name varchar(200) NOT NULL,
    user_birthday timestamp
    );
CREATE TABLE IF NOT EXISTS friends
(
    user_id int NOT NULL,
    friend_id int NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(user_id),
    CONSTRAINT fk_friend_id FOREIGN KEY(friend_id) REFERENCES users(user_id)
    );
CREATE TABLE IF NOT EXISTS user_likes
(
    film_id int NOT NULL,
    user_id int NOT NULL,
    CONSTRAINT fkul_film_id FOREIGN KEY(film_id) REFERENCES films(film_id),
    CONSTRAINT fkul_user_id FOREIGN KEY(user_id) REFERENCES users(user_id)
    );